### ISSUE TITLE
3D plotting

### ISSUE THREAD

**Issue by jruths** [ESCL-at-UTD/zonoLAB#2]
[NN_plotting_debug.zip](https://github.com/ESCL-at-UTD/zonoLAB/files/13253998/NN_plotting_debug.zip)

The attached zip file includes a matlab script and mat file.  The hybZono representation of the neural network is plotting oddly.  When plotted using slices, it seems like the hybZono looks like it should, so I think the issue is in the plotting.  It does seem to recognize that the plot is a planar object in 3D.

**Comment by jruths** [comment]
![NN_plotting_debug](https://github.com/ESCL-at-UTD/zonoLAB/assets/11622384/7da9ff30-e0ad-4f92-8e09-7d39ff3abe63)

**Comment by JKoeln** [comment]
This issue came from a bug when plotting 2D sets in 3D. The center of the set was not being accounted for properly.  This has been fixed.
