### ISSUE TITLE
Export all hybzono leaves into array (or cell array) of conZono objects

### ISSUE THREAD

**Issue by jonaswagner2826** [ESCL-at-UTD/zonoLAB#20]
Create a way to all hybzono leaves into array (or cell array) of conZono objects... likely a helper method w/in hybZono

**Comment by JChenUTD** [comment]
@JKoeln 

Hello Dr. Koeln,

I was able to fix the issue that Jonas created, however I do not have the right access to submit a pull request to zonoLab. Do you think its possible to give me access so I can send in a pull request.

![image](https://github.com/user-attachments/assets/c7c8ff3e-3739-4162-91f0-3688d8b63289)

**Comment by jruths** [comment]
@JChenUTD  Just gave you access to make the pull request.
